#!/bin/bash
# context-inject.sh - Fetch context from claude-mem and write outside the project repo
# Triggered by: beforeSubmitPrompt (runs after session-init.sh)
# Output: ~/.cursor/claude-mem/<project-slug>/context.md (opens in a separate Cursor window)

source "$(dirname "$0")/common.sh"

check_dependencies || { echo '{"continue": true}'; exit 0; }

INPUT=$(read_json_input)

WORKSPACE_ROOT=$(json_get "$INPUT" '.workspace_roots[0]')
[ -z "$WORKSPACE_ROOT" ] && WORKSPACE_ROOT="$PWD"

WORKSPACE_ROOT_NORM="${WORKSPACE_ROOT//\\//}"

SESSION_ID=$(json_get "$INPUT" '.conversation_id')
[ -z "$SESSION_ID" ] && SESSION_ID=$(json_get "$INPUT" '.generation_id')

PROJECT=$(get_project_name "$WORKSPACE_ROOT")
PROJECT_ENCODED=$(url_encode "$PROJECT")

PORT=$(get_worker_port)

ensure_worker_running "$PORT" || { echo '{"continue": true}'; exit 0; }

CONTEXT=$(run_curl -s --max-time 5 \
  "http://127.0.0.1:${PORT}/api/context/inject?project=${PROJECT_ENCODED}" 2>/dev/null)

if [ -n "$CONTEXT" ] && [ "$CONTEXT" != "null" ]; then
  EXTERNAL_DIR=$(get_external_context_dir "$WORKSPACE_ROOT")
  CONTEXT_FILE="${EXTERNAL_DIR}/context.md"
  mkdir -p "$EXTERNAL_DIR" 2>/dev/null

  cat > "$CONTEXT_FILE" << RULEFILE
# Memory Context from Past Sessions

Project: ${PROJECT}
Workspace: ${WORKSPACE_ROOT_NORM}
Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

---

${CONTEXT}

---

*Auto-generated by claude-mem. Stored outside the repo at:*
*\`${CONTEXT_FILE}\`*
*Opened in a separate Cursor window — not in the project workspace.*
RULEFILE

  remove_legacy_context_rule "$WORKSPACE_ROOT_NORM"
  open_context_in_cursor_window "$CONTEXT_FILE" "$SESSION_ID"
fi

echo '{"continue": true}'
exit 0
